"""
Seed the diseases table with knowledge base for all 38 plant disease classes.
Run with: python -m app.db.seed
"""
from app.database import SessionLocal, engine, Base
from app.models.disease import Disease


DISEASE_DATA = [
    {
        "crop_name": "Apple",
        "disease_name": "Apple scab",
        "description": "Apple scab is a common disease of plants in the rose family caused by the ascomycete fungus Venturia inaequalis. The disease affects both leaves and fruit, causing significant economic losses in apple orchards worldwide.",
        "symptoms": [
            "Olive-green to brown velvety spots on leaf surfaces",
            "Yellowing and early leaf drop",
            "Dark, scabby lesions on fruit skin",
            "Cracked and deformed fruit",
            "Lesions on young shoots and blossoms",
        ],
        "treatment": [
            "Apply fungicides (captan, myclobutanil) at bud break and every 7-10 days during wet weather",
            "Remove and destroy infected fallen leaves",
            "Prune trees to improve air circulation",
            "Apply liquid lime sulfur during dormant season",
        ],
        "prevention": [
            "Plant scab-resistant apple varieties",
            "Maintain proper tree spacing for good air circulation",
            "Rake and dispose of fallen leaves in autumn",
            "Monitor weather conditions and apply preventive fungicides before rain",
            "Avoid overhead irrigation",
        ],
    },
    {
        "crop_name": "Apple",
        "disease_name": "Black rot",
        "description": "Black rot of apple is caused by the fungus Botryosphaeria obtusa. It can infect all aboveground parts of the plant including fruit, leaves, and bark, causing significant crop losses.",
        "symptoms": [
            "Brown to black circular lesions on leaves (frogeye leaf spot)",
            "Mummified fruit turning black",
            "Cankers on branches with rough, cracked bark",
            "Rotted fruit with concentric rings",
            "Premature fruit drop",
        ],
        "treatment": [
            "Remove and destroy mummified fruit and cankered wood",
            "Apply captan or thiophanate-methyl fungicides",
            "Prune infected branches 8-10 inches below visible cankers",
            "Sterilize pruning tools between cuts",
        ],
        "prevention": [
            "Maintain tree vigor through proper fertilization and irrigation",
            "Prune dead and diseased wood annually",
            "Remove wild or abandoned apple trees nearby",
            "Apply preventive fungicide sprays from pink bud stage",
            "Ensure good drainage and air circulation",
        ],
    },
    {
        "crop_name": "Apple",
        "disease_name": "Cedar apple rust",
        "description": "Cedar apple rust is caused by Gymnosporangium juniperi-virginianae, a fungus requiring two host plants to complete its life cycle: Eastern red cedar (or other junipers) and apple or crabapple trees.",
        "symptoms": [
            "Bright orange-yellow spots on upper leaf surfaces",
            "Tube-like structures (aecia) on the undersides of leaves",
            "Pale yellow lesions on fruit",
            "Premature defoliation in severe cases",
            "Swollen, distorted fruit",
        ],
        "treatment": [
            "Apply myclobutanil or propiconazole fungicides from pink through petal fall",
            "Remove nearby Eastern red cedar trees if possible",
            "Apply protective fungicides before and after infection periods",
        ],
        "prevention": [
            "Plant rust-resistant apple varieties",
            "Remove galls from cedar trees in early spring before spores release",
            "Avoid planting apples near cedar/juniper trees",
            "Monitor weather for high-risk periods (warm, wet spring)",
            "Maintain tree health with proper nutrition",
        ],
    },
    {
        "crop_name": "Apple",
        "disease_name": "Healthy",
        "description": "This apple plant is healthy with no signs of disease. Healthy apple trees display vibrant green foliage, strong branch structure, and well-developed fruit.",
        "symptoms": ["No disease symptoms present", "Vibrant green leaves", "Normal fruit development"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Maintain regular pruning schedule",
            "Apply balanced fertilizer as needed",
            "Monitor for early signs of pests and disease",
            "Ensure proper irrigation",
        ],
    },
    {
        "crop_name": "Blueberry",
        "disease_name": "Healthy",
        "description": "This blueberry plant is healthy with no signs of disease. Healthy blueberry plants show lush green foliage and normal fruit production.",
        "symptoms": ["No disease symptoms present"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Maintain soil pH between 4.5-5.5",
            "Provide adequate mulching",
            "Ensure good drainage",
            "Monitor for pests regularly",
        ],
    },
    {
        "crop_name": "Cherry",
        "disease_name": "Powdery mildew",
        "description": "Cherry powdery mildew is caused by Podosphaera clandestina, a fungal pathogen that produces a distinctive white powdery coating on plant surfaces. It thrives in warm, dry conditions with high humidity.",
        "symptoms": [
            "White powdery coating on young leaves and shoots",
            "Distorted and curled new growth",
            "Premature leaf drop",
            "Reduced fruit set",
            "Stunted shoot growth",
        ],
        "treatment": [
            "Apply sulfur-based fungicides at first sign of infection",
            "Use potassium bicarbonate sprays",
            "Apply neem oil as an organic option",
            "Remove and destroy heavily infected shoots",
        ],
        "prevention": [
            "Plant resistant cherry varieties",
            "Ensure adequate spacing between trees",
            "Avoid excessive nitrogen fertilization",
            "Apply preventive fungicide sprays during susceptible growth stages",
            "Improve air circulation through pruning",
        ],
    },
    {
        "crop_name": "Cherry",
        "disease_name": "Healthy",
        "description": "This cherry plant is healthy with no signs of disease.",
        "symptoms": ["No disease symptoms present"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Annual pruning for shape and air circulation",
            "Regular monitoring for pests",
            "Balanced fertilization program",
        ],
    },
    {
        "crop_name": "Corn (maize)",
        "disease_name": "Cercospora leaf spot Gray leaf spot",
        "description": "Gray leaf spot (GLS) is caused by the fungus Cercospora zeae-maydis and is one of the most significant foliar diseases of corn worldwide. It thrives in warm, humid conditions and can cause yield losses of 20-50%.",
        "symptoms": [
            "Rectangular, gray to tan lesions with parallel sides between leaf veins",
            "Lesions initially appear water-soaked, then turn tan to gray",
            "Lesions can merge, causing large areas of blighted tissue",
            "Severe cases result in premature death of leaves",
            "Disease progresses from lower to upper leaves",
        ],
        "treatment": [
            "Apply strobilurin or triazole fungicides at VT or R1 growth stage",
            "Foliar fungicide application when conditions favor disease",
            "Scout fields regularly and spray when threshold is reached",
        ],
        "prevention": [
            "Plant resistant or tolerant hybrids",
            "Rotate crops — avoid continuous corn",
            "Till to reduce infected crop residue",
            "Ensure adequate plant spacing for air circulation",
            "Avoid planting in low-lying areas with poor drainage",
        ],
    },
    {
        "crop_name": "Corn (maize)",
        "disease_name": "Common rust",
        "description": "Common rust of corn is caused by the fungus Puccinia sorghi. While it rarely causes significant losses in field corn, it can be economically important in sweet corn and popcorn.",
        "symptoms": [
            "Small, circular to elongated powdery pustules on both leaf surfaces",
            "Pustules are cinnamon-brown to dark brown",
            "Pustules may appear on husks, sheaths, and stalks in severe cases",
            "Heavy infection causes premature leaf death",
            "Leaves turn yellow, then brown",
        ],
        "treatment": [
            "Apply foliar fungicides (mancozeb, chlorothalonil, or triazoles) at first sign",
            "Spray when pustules first appear on lower leaves",
        ],
        "prevention": [
            "Plant resistant hybrids",
            "Early planting to avoid peak spore periods",
            "Monitor fields regularly, especially during cool and humid weather",
        ],
    },
    {
        "crop_name": "Corn (maize)",
        "disease_name": "Northern Leaf Blight",
        "description": "Northern corn leaf blight (NCLB) is caused by the fungus Setosphaeria turcica. It is a major foliar disease in areas with moderate temperatures and high humidity, capable of causing yield losses up to 30-50%.",
        "symptoms": [
            "Long, elliptical, tan to gray-green lesions (1-6 inches long)",
            "Lesions have wavy margins and appear on lower leaves first",
            "Lesions become grayish-green as fungal spores develop",
            "Severe infections lead to premature plant death",
            "Dark spore masses visible on lesion surfaces in humid conditions",
        ],
        "treatment": [
            "Apply triazole or strobilurin fungicides at VT-R1 stage",
            "Fungicide application is most effective when applied before symptoms appear",
            "Repeat application may be needed in severe epidemics",
        ],
        "prevention": [
            "Plant resistant hybrids — most effective management strategy",
            "Crop rotation to reduce inoculum levels",
            "Tillage to bury infected residue",
            "Avoid planting susceptible varieties in high-risk areas",
        ],
    },
    {
        "crop_name": "Corn (maize)",
        "disease_name": "Healthy",
        "description": "This corn plant is healthy with no signs of disease.",
        "symptoms": ["No disease symptoms present"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Rotate crops annually",
            "Use certified disease-free seeds",
            "Scout fields regularly",
            "Maintain proper plant nutrition",
        ],
    },
    {
        "crop_name": "Grape",
        "disease_name": "Black rot",
        "description": "Grape black rot is caused by the fungus Guignardia bidwellii. It is one of the most destructive diseases of grapes in the eastern United States and can cause total crop loss in susceptible varieties during wet seasons.",
        "symptoms": [
            "Small, tan circular spots with dark borders on leaves",
            "Black, shriveled mummified berries",
            "Infected berries harden and remain attached to clusters",
            "Salmon-colored spore masses visible in leaf spots",
            "Cankers on young shoots",
        ],
        "treatment": [
            "Apply mancozeb, captan, or myclobutanil fungicides from bud break through veraison",
            "Remove and destroy mummified berries",
            "Prune and remove infected canes",
        ],
        "prevention": [
            "Remove mummies from vines and ground before bud break",
            "Train vines to improve air circulation",
            "Apply preventive fungicides, especially before and after rainy periods",
            "Plant resistant varieties where possible",
        ],
    },
    {
        "crop_name": "Grape",
        "disease_name": "Esca (Black Measles)",
        "description": "Esca, also known as black measles or apoplexy, is a complex grapevine trunk disease caused by a consortium of wood-decaying fungi. It is a serious and widespread disease affecting vineyards worldwide.",
        "symptoms": [
            "Tiger stripe pattern on leaves — interveinal chlorosis and necrosis",
            "Black spots or streaks on berries (measles symptom)",
            "Sudden wilting and collapse of entire vines (apoplexy)",
            "White rot in the wood",
            "Stunted shoot growth",
        ],
        "treatment": [
            "No curative chemical treatments available",
            "Remove and destroy affected wood",
            "Protect pruning wounds with wound sealants",
            "Double pruning technique (Simonit & Sirch method)",
        ],
        "prevention": [
            "Minimize large pruning wounds",
            "Apply wound protection products immediately after pruning",
            "Prune during dry weather",
            "Avoid pruning during wet conditions",
            "Use healthy planting material",
        ],
    },
    {
        "crop_name": "Grape",
        "disease_name": "Leaf blight (Isariopsis Leaf Spot)",
        "description": "Grape leaf blight caused by Pseudocercospora vitis (formerly Isariopsis clavispora) is a foliar disease that can cause significant defoliation in warm, humid regions.",
        "symptoms": [
            "Irregular dark brown spots on upper leaf surface",
            "Gray to olive-colored fungal growth on lower leaf surface",
            "Premature defoliation",
            "Reduced photosynthesis and vine vigor",
            "Reduced fruit quality and size",
        ],
        "treatment": [
            "Apply copper-based fungicides or mancozeb",
            "Spray every 10-14 days during humid conditions",
            "Remove severely infected leaves",
        ],
        "prevention": [
            "Maintain open canopy for air circulation",
            "Avoid overhead irrigation",
            "Apply preventive fungicides during susceptible periods",
            "Remove and destroy fallen infected leaves",
        ],
    },
    {
        "crop_name": "Grape",
        "disease_name": "Healthy",
        "description": "This grape plant is healthy with no signs of disease.",
        "symptoms": ["No disease symptoms present"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Regular canopy management",
            "Proper pruning techniques",
            "Preventive fungicide program",
            "Monitor vine nutrition",
        ],
    },
    {
        "crop_name": "Orange",
        "disease_name": "Haunglongbing (Citrus greening)",
        "description": "Huanglongbing (HLB), also known as citrus greening, is considered the most destructive citrus disease in the world. Caused by the bacterium Candidatus Liberibacter asiaticus and spread by the Asian citrus psyllid, there is currently no cure.",
        "symptoms": [
            "Yellow shoots (blotchy mottle pattern on leaves)",
            "Asymmetrical yellowing that does not follow leaf veins",
            "Small, lopsided fruit that remains green",
            "Bitter, unsaleable fruit",
            "Dieback of shoots and branches",
            "Tree decline and death over several years",
        ],
        "treatment": [
            "No cure currently available",
            "Remove and destroy infected trees to prevent spread",
            "Aggressive psyllid vector control with insecticides",
            "Nutritional therapy (trunk injections) may temporarily sustain trees",
        ],
        "prevention": [
            "Use certified disease-free nursery stock",
            "Control Asian citrus psyllid populations with insecticides",
            "Inspect trees regularly for psyllids and disease symptoms",
            "Quarantine measures to prevent movement of infected material",
            "Report suspected cases to local agricultural authorities",
        ],
    },
    {
        "crop_name": "Peach",
        "disease_name": "Bacterial spot",
        "description": "Bacterial spot of peach is caused by Xanthomonas arboricola pv. pruni. It is one of the most common and destructive diseases of peaches and nectarines, affecting leaves, fruit, and twigs.",
        "symptoms": [
            "Water-soaked spots on leaves that turn purplish-black",
            "Spots surrounded by yellow halos",
            "Premature defoliation",
            "Sunken, water-soaked spots on fruit that become scabby",
            "Cankers on twigs with gummy exudate",
        ],
        "treatment": [
            "Apply copper-based bactericides from bud break through early summer",
            "Use oxytetracycline (if permitted) as an alternative bactericide",
            "Prune and destroy cankered twigs",
        ],
        "prevention": [
            "Plant resistant or tolerant peach varieties",
            "Avoid sites with poor air drainage",
            "Protect trees from injury (wind, insects) that creates entry points",
            "Apply preventive copper sprays before rain events",
        ],
    },
    {
        "crop_name": "Peach",
        "disease_name": "Healthy",
        "description": "This peach plant is healthy with no signs of disease.",
        "symptoms": ["No disease symptoms present"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Regular dormant pruning",
            "Annual copper spray program",
            "Pest monitoring program",
            "Proper thinning for air circulation",
        ],
    },
    {
        "crop_name": "Pepper, bell",
        "disease_name": "Bacterial spot",
        "description": "Bacterial spot of pepper is caused by Xanthomonas euvesicatoria. It affects both leaves and fruit and is favored by warm, wet weather. It can cause serious losses, especially in field production.",
        "symptoms": [
            "Small, water-soaked spots on leaves that turn brown with yellow halos",
            "Raised, scabby lesions on green fruit",
            "Fruit lesions become sunken and water-soaked",
            "Premature fruit drop",
            "Defoliation in severe cases",
        ],
        "treatment": [
            "Apply copper hydroxide plus mancozeb on a 5-7 day schedule",
            "Use bactericide-resistant cultivars",
            "Remove and destroy infected plant material",
        ],
        "prevention": [
            "Use disease-free certified seed",
            "Treat seed with hot water (50°C for 25 minutes)",
            "Avoid overhead irrigation",
            "Rotate crops — avoid peppers and tomatoes in same field for 2-3 years",
            "Minimize plant wounding during field operations",
        ],
    },
    {
        "crop_name": "Pepper, bell",
        "disease_name": "Healthy",
        "description": "This bell pepper plant is healthy with no signs of disease.",
        "symptoms": ["No disease symptoms present"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Use certified disease-free transplants",
            "Practice crop rotation",
            "Avoid working in fields when wet",
            "Maintain proper plant nutrition",
        ],
    },
    {
        "crop_name": "Potato",
        "disease_name": "Early blight",
        "description": "Early blight of potato is caused by Alternaria solani. It is a common and widespread foliar disease that reduces photosynthetic capacity and can cause significant yield losses, particularly in stressed plants.",
        "symptoms": [
            "Dark brown to black lesions with concentric rings (target board pattern)",
            "Lesions surrounded by yellow tissue",
            "Begins on older, lower leaves and progresses upward",
            "Severe cases cause complete defoliation",
            "Dark, sunken lesions on tubers",
        ],
        "treatment": [
            "Apply fungicides (chlorothalonil, mancozeb, or azoxystrobin) preventively",
            "Begin sprays at early bud stage or at first sign of disease",
            "Maintain spray intervals of 7-10 days",
        ],
        "prevention": [
            "Use certified disease-free seed potatoes",
            "Maintain adequate soil moisture and nutrition",
            "Rotate crops — avoid planting potatoes after tomatoes or peppers",
            "Destroy infected crop debris after harvest",
            "Plant early-maturing varieties to escape late-season disease",
        ],
    },
    {
        "crop_name": "Potato",
        "disease_name": "Late blight",
        "description": "Potato late blight is caused by the oomycete pathogen Phytophthora infestans. This is the same disease that caused the Irish Famine in the 1840s. It remains one of the most economically important plant diseases worldwide.",
        "symptoms": [
            "Water-soaked, pale green to brown lesions on leaves",
            "White sporulation on the underside of lesions in humid conditions",
            "Rapid spread causing entire fields to collapse within days",
            "Dark, firm rot on tubers",
            "Infected tubers have reddish-brown granular rot",
        ],
        "treatment": [
            "Apply protectant fungicides (chlorothalonil, mancozeb) preventively",
            "Apply systemic fungicides (metalaxyl, cymoxanil) at first sign",
            "Spray every 5-7 days during high-risk periods",
            "Destroy infected haulm (vines) before harvest",
        ],
        "prevention": [
            "Plant certified disease-free seed potatoes",
            "Use resistant varieties",
            "Destroy volunteer potato plants",
            "Monitor weather forecasts using disease warning systems (BLITECAST)",
            "Ensure good air circulation by proper plant spacing",
            "Hill plants to protect tubers",
        ],
    },
    {
        "crop_name": "Potato",
        "disease_name": "Healthy",
        "description": "This potato plant is healthy with no signs of disease.",
        "symptoms": ["No disease symptoms present"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Use certified seed potatoes",
            "Practice 3-4 year crop rotation",
            "Scout fields weekly",
            "Maintain balanced plant nutrition",
        ],
    },
    {
        "crop_name": "Raspberry",
        "disease_name": "Healthy",
        "description": "This raspberry plant is healthy with no signs of disease.",
        "symptoms": ["No disease symptoms present"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Annual cane removal after fruiting",
            "Weed control",
            "Adequate spacing for air circulation",
            "Regular monitoring for pests",
        ],
    },
    {
        "crop_name": "Soybean",
        "disease_name": "Healthy",
        "description": "This soybean plant is healthy with no signs of disease.",
        "symptoms": ["No disease symptoms present"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Use resistant varieties",
            "Rotate crops regularly",
            "Scout fields weekly during growing season",
            "Maintain proper plant population",
        ],
    },
    {
        "crop_name": "Squash",
        "disease_name": "Powdery mildew",
        "description": "Powdery mildew of squash is caused by Podosphaera xanthii (formerly Sphaerotheca fuliginea). It is the most common and easily recognized disease of cucurbits, affecting squash, pumpkins, cucumbers, and melons.",
        "symptoms": [
            "White to gray powdery coating on upper and lower leaf surfaces",
            "Yellowing of affected leaves",
            "Premature defoliation",
            "Reduced fruit quality and yield",
            "Infected stems may also show white powder",
        ],
        "treatment": [
            "Apply sulfur, potassium bicarbonate, or neem oil at first sign",
            "Use systemic fungicides (myclobutanil, trifloxystrobin) in severe cases",
            "Remove and destroy heavily infected leaves",
        ],
        "prevention": [
            "Plant resistant varieties",
            "Ensure adequate plant spacing",
            "Avoid overhead irrigation",
            "Apply preventive organic sprays (baking soda solution) weekly",
            "Maintain healthy plants with balanced nutrition",
        ],
    },
    {
        "crop_name": "Strawberry",
        "disease_name": "Leaf scorch",
        "description": "Strawberry leaf scorch is caused by the fungus Diplocarpon earlianum. It is one of the most common and damaging foliar diseases of strawberries, causing reduced plant vigor and productivity.",
        "symptoms": [
            "Irregular dark purplish spots on upper leaf surface",
            "Spots lack distinct borders, giving a 'scorched' appearance",
            "Centers of spots turn tan to gray-brown",
            "Severe infection causes leaf death",
            "Petioles and fruit trusses may also be affected",
        ],
        "treatment": [
            "Apply captan or copper-based fungicides at flowering",
            "Continue applications every 7-14 days during wet weather",
            "Remove and destroy infected leaves",
        ],
        "prevention": [
            "Plant resistant cultivars",
            "Renovate plantings annually by mowing and thinning",
            "Avoid overhead irrigation",
            "Ensure good air circulation within planting",
            "Use raised beds with good drainage",
        ],
    },
    {
        "crop_name": "Strawberry",
        "disease_name": "Healthy",
        "description": "This strawberry plant is healthy with no signs of disease.",
        "symptoms": ["No disease symptoms present"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Annual renovation of planting",
            "Proper plant spacing",
            "Use of disease-free runners",
            "Regular weed control",
        ],
    },
    {
        "crop_name": "Tomato",
        "disease_name": "Bacterial spot",
        "description": "Bacterial spot of tomato is caused by Xanthomonas perforans. It is a serious disease in warm, wet climates and can cause significant losses in fruit quality and yield.",
        "symptoms": [
            "Small, water-soaked spots on leaves, stems, and fruit",
            "Spots turn dark brown, surrounded by yellow halos",
            "Defoliation in severe cases",
            "Raised, scabby lesions on green fruit",
            "Fruit spots do not penetrate deep into flesh",
        ],
        "treatment": [
            "Apply copper-based bactericides plus mancozeb on 5-7 day intervals",
            "Remove and destroy infected plant material",
            "Avoid working with wet plants",
        ],
        "prevention": [
            "Use disease-free certified seeds and transplants",
            "Practice 2-3 year crop rotation",
            "Avoid overhead irrigation",
            "Sanitize equipment between fields",
            "Use resistant varieties when available",
        ],
    },
    {
        "crop_name": "Tomato",
        "disease_name": "Early blight",
        "description": "Early blight of tomato is caused by Alternaria solani and Alternaria tomatophila. It is one of the most common foliar diseases of tomato and can cause significant defoliation and yield losses.",
        "symptoms": [
            "Dark brown lesions with concentric rings forming a target pattern",
            "Lesions surrounded by bright yellow tissue",
            "Disease begins on older, lower leaves",
            "Stems may show dark lesions (collar rot in seedlings)",
            "Fruit lesions appear near the stem end",
        ],
        "treatment": [
            "Apply fungicides (chlorothalonil, mancozeb, azoxystrobin) every 7-10 days",
            "Remove infected lower leaves",
            "Apply calcium sprays to maintain plant health",
        ],
        "prevention": [
            "Use disease-free certified seed",
            "Practice crop rotation with non-solanaceous crops",
            "Stake plants and maintain proper spacing",
            "Mulch around plants to reduce soil splash",
            "Water at the base of plants, not overhead",
        ],
    },
    {
        "crop_name": "Tomato",
        "disease_name": "Late blight",
        "description": "Tomato late blight is caused by Phytophthora infestans. It can destroy entire tomato fields within days under favorable conditions (cool nights, warm days, and wet weather).",
        "symptoms": [
            "Water-soaked, pale green lesions on leaves that turn dark brown",
            "White sporulation on the underside of lesions",
            "Rapid spread causing complete plant collapse",
            "Dark brown, greasy-looking lesions on stems",
            "Firm, brown rot extending into fruit flesh",
        ],
        "treatment": [
            "Apply fungicides (chlorothalonil, copper, cymoxanil) preventively",
            "Use systemic fungicides at first sign of disease",
            "Remove and destroy infected plants or plant parts",
            "Do not compost infected material",
        ],
        "prevention": [
            "Plant resistant varieties",
            "Use certified disease-free transplants",
            "Avoid overhead irrigation",
            "Monitor weather forecasts for high-risk conditions",
            "Inspect plants daily during cool, wet weather",
            "Destroy volunteer tomato and potato plants",
        ],
    },
    {
        "crop_name": "Tomato",
        "disease_name": "Leaf Mold",
        "description": "Tomato leaf mold is caused by the fungus Fulvia fulva (formerly Cladosporium fulvum). It is primarily a disease of tomatoes in greenhouses and high-humidity outdoor environments.",
        "symptoms": [
            "Pale green to yellow spots on upper leaf surface",
            "Olive-green to brown velvety fungal growth on lower leaf surface",
            "Leaves curl, wither, and drop",
            "Flowers may be infected, reducing fruit set",
            "Fruit infections are rare but can occur",
        ],
        "treatment": [
            "Apply copper-based fungicides or chlorothalonil",
            "Improve ventilation in greenhouses",
            "Reduce relative humidity to below 85%",
            "Remove infected leaves",
        ],
        "prevention": [
            "Use resistant varieties (most available in greenhouse types)",
            "Maintain greenhouse humidity below 85%",
            "Ensure adequate spacing and ventilation",
            "Avoid wetting foliage when irrigating",
            "Sanitize greenhouse structures between crops",
        ],
    },
    {
        "crop_name": "Tomato",
        "disease_name": "Septoria leaf spot",
        "description": "Septoria leaf spot is caused by the fungus Septoria lycopersici. It is one of the most destructive diseases of tomato foliage in the eastern United States, causing severe defoliation that weakens plants and reduces yield.",
        "symptoms": [
            "Circular spots with dark brown borders and gray-white centers",
            "Small dark specks (pycnidia) visible in the center of spots",
            "Spots first appear on the lowest, oldest leaves",
            "Yellowing and defoliation of infected leaves",
            "Spots rarely occur on fruit",
        ],
        "treatment": [
            "Apply chlorothalonil, mancozeb, or copper fungicides",
            "Spray every 7-10 days during wet weather",
            "Remove lower infected leaves to slow spread",
        ],
        "prevention": [
            "Use disease-free seed and transplants",
            "Rotate crops — avoid tomatoes on same ground for 3 years",
            "Stake plants to improve air flow",
            "Mulch soil to reduce splash dispersal",
            "Avoid working with wet plants",
        ],
    },
    {
        "crop_name": "Tomato",
        "disease_name": "Spider mites Two-spotted spider mite",
        "description": "Two-spotted spider mite (Tetranychus urticae) is a major pest of tomatoes. While technically not a fungal disease, the feeding damage causes characteristic leaf symptoms and can severely reduce yield.",
        "symptoms": [
            "Fine stippling or bronzing of leaves",
            "Fine silk webbing on the undersides of leaves",
            "Leaves turn yellow, bronze, or brown",
            "Severe infestations cause premature leaf drop",
            "Tiny moving dots (mites) visible with a hand lens",
        ],
        "treatment": [
            "Apply miticide sprays (abamectin, bifenazate, or spiromesifen)",
            "Use insecticidal soap or neem oil for organic control",
            "Spray the undersides of leaves thoroughly",
            "Repeat applications every 5-7 days",
        ],
        "prevention": [
            "Avoid water stress which makes plants more susceptible",
            "Minimize use of broad-spectrum insecticides that kill natural enemies",
            "Introduce predatory mites (Phytoseiulus persimilis) as biocontrol",
            "Monitor plants regularly, especially during hot, dry weather",
            "Use reflective mulches to repel mites",
        ],
    },
    {
        "crop_name": "Tomato",
        "disease_name": "Target Spot",
        "description": "Target spot of tomato is caused by Corynespora cassiicola. It affects leaves, stems, and fruit, and can cause significant defoliation and crop losses under humid conditions.",
        "symptoms": [
            "Brown lesions with concentric rings (target appearance) on leaves",
            "Lesions have yellow halos",
            "Small dark spots on fruit surface",
            "Stem lesions can cause plant death",
            "Defoliation starts from lower leaves",
        ],
        "treatment": [
            "Apply fungicides (chlorothalonil, azoxystrobin, or difenoconazole)",
            "Spray every 7-14 days during wet conditions",
            "Remove severely infected plant material",
        ],
        "prevention": [
            "Plant resistant varieties where available",
            "Ensure adequate spacing and air circulation",
            "Avoid overhead irrigation",
            "Practice crop rotation",
            "Remove and destroy infected crop debris",
        ],
    },
    {
        "crop_name": "Tomato",
        "disease_name": "Tomato Yellow Leaf Curl Virus",
        "description": "Tomato yellow leaf curl virus (TYLCV) is a devastating viral disease transmitted by the whitefly Bemisia tabaci. It causes severe yield losses and is one of the most important tomato diseases in tropical and subtropical regions.",
        "symptoms": [
            "Severe upward curling and yellowing of leaves",
            "Stunted plant growth",
            "Flower drop and fruit set failure",
            "Leaves appear small and crumpled",
            "Plants infected early show severe stunting",
        ],
        "treatment": [
            "No cure for infected plants",
            "Remove and destroy infected plants immediately",
            "Apply insecticides to control whitefly vectors",
            "Use yellow sticky traps to monitor whitefly populations",
        ],
        "prevention": [
            "Plant TYLCV-resistant or tolerant varieties",
            "Use insecticide-treated seedlings",
            "Cover plants with insect-proof nets",
            "Remove weed hosts near fields",
            "Control whitefly populations with imidacloprid or other systemic insecticides",
            "Avoid planting near older infected fields",
        ],
    },
    {
        "crop_name": "Tomato",
        "disease_name": "Tomato mosaic virus",
        "description": "Tomato mosaic virus (ToMV) is a highly stable and contagious plant virus that can persist in soil and plant debris for years. It is mechanically transmitted through sap contact and can cause significant yield losses.",
        "symptoms": [
            "Mosaic pattern of light and dark green on leaves",
            "Leaf distortion — leaves appear narrow, fernlike, or twisted",
            "Stunted growth",
            "Reduced fruit size and irregular ripening",
            "Fruit may show internal browning",
        ],
        "treatment": [
            "No effective chemical treatment for viral infections",
            "Remove and destroy infected plants",
            "Disinfect tools and hands with soap or bleach solution",
        ],
        "prevention": [
            "Use certified virus-free seed",
            "Plant resistant varieties carrying the Tm-2² resistance gene",
            "Disinfect tools and stakes between plants",
            "Wash hands thoroughly before handling plants",
            "Control tobacco use near plants — tobacco workers can spread the virus",
            "Rotate crops and remove infected plant debris",
        ],
    },
    {
        "crop_name": "Tomato",
        "disease_name": "Healthy",
        "description": "This tomato plant is healthy with no signs of disease.",
        "symptoms": ["No disease symptoms present"],
        "treatment": ["No treatment needed"],
        "prevention": [
            "Practice crop rotation",
            "Use disease-resistant varieties",
            "Monitor for pests and diseases weekly",
            "Maintain proper plant nutrition and irrigation",
        ],
    },
]


def seed_diseases(db):
    existing = db.query(Disease).count()
    if existing > 0:
        print(f"[INFO] Diseases table already has {existing} records. Skipping seed.")
        return

    for data in DISEASE_DATA:
        disease = Disease(**data)
        db.add(disease)

    db.commit()
    print(f"[INFO] Seeded {len(DISEASE_DATA)} disease records.")


if __name__ == "__main__":
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        seed_diseases(db)
    finally:
        db.close()
